# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

def abstract_pods
    pod 'ObjectMapper', '~> 1.0'
end

target 'iOSSwiftStarter' do
    abstract_pods
    pod 'Alamofire', '~> 3.5.0'
    pod 'AlamofireObjectMapper', '~> 3.0.2'
    pod 'ReactKit'
    pod 'Kugel', '~> 0.1.0'
    pod 'CoreStore', '~> 2.1.0'
    pod 'Hakuba', '~> 2.1.0'
    pod 'Kingfisher', '~> 2.6.1'
    pod 'AsyncSwift', '~> 1.6.4'
    pod 'StatefulViewController', '~> 1.0'
end

def testing_pods
    abstract_pods
    pod 'Quick'
    pod 'Nimble'
end

target 'iOSSwiftStarterTests' do
    testing_pods
end

target 'iOSSwiftStarterUITests' do
end

# Use Legacy Swift Language Version
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |configuration|
      configuration.build_settings['SWIFT_VERSION'] = "2.3"
    end
  end
end